- name: link settings.json
  file:
    src: "{{ role_path }}/files/settings.json"
    dest: "{{ ansible_env.HOME }}/Library/Application Support/Code/User/settings.json"
    state: link
    force: yes
  tags: code

- name: install code extensions
  command: code --install-extension {{ item|quote }}
  with_items: "{{ code_extensions }}"
  tags: code
