homebrew_taps: []

homebrew_packages:
  - { name: autoconf }
  - { name: clang-format }
  - { name: coreutils }
  - { name: cue }
  - { name: curl }
  - { name: direnv }
  - { name: findutils }
  - { name: gh }
  - { name: ghq }
  - { name: git }
  - { name: go }
  - { name: gpg }
  - { name: graphviz }
  - { name: grpcurl }
  - { name: jq }
  - { name: kubectx }
  - { name: kube-ps1 }
  - { name: openssl }
  - { name: peco }
  - { name: php }
  - { name: pinentry-mac }
  - { name: plantuml }
  - { name: readline }
  - { name: rename }
  - { name: ripgrep }
  - { name: screen }
  - { name: source-highlight }
  - { name: stern }
  - { name: vim }
  - { name: wget }
  - { name: zsh }

homebrew_links:
  - { name: curl }
  #- { name: openssl } # error: Package not installed: openssl.

homebrew_cask_packages:
  - { name: docker }
  - { name: font-hack }
  - { name: tailscale }
  - { name: temurin }
  - { name: visual-studio-code }

zsh_bin: /opt/homebrew/bin/zsh
